services:
  kmp_db:
    image: postgres:17.5-alpine3.21
    container_name: kmp_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kmp_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d kmp_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_app_data:
    driver: local