services:
  - type: web
    name: kmp-server
    runtime: docker
    plan: free
    region: oregon
    rootDir: KeepMyPlanet
    dockerfilePath: ./KeepMyPlanet/server/Dockerfile
    dockerContext: ./KeepMyPlanet
    healthCheckPath: /
    envVars:
      - key: KTOR_STORAGE_JDBCURL
        value: "jdbc:postgresql://${kmp-db.host}:${kmp-db.port}/${kmp-db.databaseName}"
      - key: KTOR_STORAGE_USER
        fromDatabase:
          name: kmp-db
          property: user
      - key: KTOR_STORAGE_PASSWORD
        fromDatabase:
          name: kmp-db
          property: password
      - key: KTOR_JWT_SECRET
        generateValue: true
      - key: KTOR_SERVER_BASEURL
        value: ${RENDER_EXTERNAL_URL}
      - key: KTOR_CLOUDINARY_URL
        sync: false

  - type: web
    name: kmp-webapp
    runtime: static
    rootDir: KeepMyPlanet
    buildCommand: |
      ./gradlew :composeApp:wasmJsBrowserDistribution
      sed -i "s|http://localhost:1904|${kmp-server.url}|g" ./composeApp/build/dist/wasmJs/productionExecutable/composeApp.js
    staticPublishPath: ./composeApp/build/dist/wasmJs/productionExecutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - "KeepMyPlanet/composeApp/**"
        - "KeepMyPlanet/shared/**"
        - "KeepMyPlanet/gradle/**"
        - "KeepMyPlanet/*.kts"
        - "KeepMyPlanet/gradlew"
      ignoredPaths:
        - "**.test.*"
        - "**.md"

databases:
  - name: kmp-db
    databaseName: kmp_db
    user: user
    plan: free
    region: oregon
    postgresMajorVersion: "16"