services:
  - type: web
    name: kmp-server
    runtime: docker
    plan: free
    region: oregon
    rootDir: KeepMyPlanet/server
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: KTOR_STORAGE_JDBCURL
        value: "jdbc:postgresql://${kmp-db.host}:${kmp-db.port}/${kmp-db.databaseName}"
      - key: KTOR_STORAGE_USER
        fromDatabase:
          name: kmp-db
          property: user
      - key: KTOR_STORAGE_PASSWORD
        fromDatabase:
          name: kmp-db
          property: password
      - key: KTOR_JWT_SECRET
        generateValue: true
      - key: KTOR_SERVER_BASEURL
        value: ${RENDER_EXTERNAL_URL}
      - key: KTOR_CLOUDINARY_URL
        sync: false


  - type: web
    name: kmp-webapp
    runtime: docker
    plan: free
    region: oregon
    rootDir: KeepMyPlanet/composeApp
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: KMP_SERVER_URL
        value: ${kmp-server.url}


databases:
  - name: kmp-db
    databaseName: kmp_db
    user: user
    plan: free
    region: oregon
    postgresMajorVersion: "16"