databases:
  - name: kmp-db
    plan: free

services:
  - type: web
    name: kmp-server
    plan: free
    rootDir: KeepMyPlanet
    buildCommand: "./build.sh"
    startCommand: "KeepMyPlanet/server/build/install/server/bin/server"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kmp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false