@startuml

enum EventStatus {
  PLANNED
  IN_PROGRESS
  COMPLETED
  CANCELLED
}

enum ZoneStatus {
  REPORTED
  CLEANING_SCHEDULED
  CLEANED
}

class User {
  name: Name
  email: Email <<unique>>
  password: Password
}

class Zone {
  address: Address
  description: Description
  area: Location
  reported: Date
  photos: List<Photo>
  critical: Boolean
}

class Event {
  title: Title
  description: Description
  start: DateTime
  period: Duration
}

class Message {
  content: MessageContent
  timestamp: DateTime
}

User <- Event : organizer
User <- Zone : reporter
User <- Message : sender
User "*" -- "*" Event : participants <

Event --* Zone : events
Event *-- "*" Message : messages
Event -> EventStatus : status

Zone -up-> ZoneStatus : status

hide empty members

@enduml