@startuml

enum EventStatus {
  PLANNED
  IN_PROGRESS
  COMPLETED
  CANCELLED
}

enum ZoneStatus {
  REPORTED
  CLEANING_SCHEDULED
  CLEANED
}

enum ZoneSeverity {
    UNKNOWN
    LOW
    MEDIUM
    HIGH
}

class User {
  name: Name
  email: Email <<unique>>
  password: Password
}

class Zone {
  description: Description
  area: Location
  reported: Date
  photos: List<Photo>
}

class Event {
  title: Title
  description: Description
  period: Duration
}

class Message {
  chatPosition: Int
  content: MessageContent
  timestamp: DateTime
}

User <- Event : organizer
User <- Zone : reporter
User <- Message : sender
User "*" -- "*" Event : participants <

Event "*" --* Zone : events
Event *-- "*" Message : messages
Event -> EventStatus : status

Zone -up-> ZoneStatus : status
Zone -left-> ZoneSeverity : severity
Zone -right-> Message : messages
hide empty members

@enduml