@startuml

' enumerações
enum EventStatus {
  'evento planeado e agendado, mas que ainda não aconteceu'
  PLANNED
  'evento que está a acontecer.'
  IN_PROGRESS
  'evento concluido'
  COMPLETED
  'evento que foi cancelado por algum motivo'
  CANCELLED
}

enum ZoneStatus {
  'zona que foi reportada por um utilizador, mas ainda não foi limpa'
  REPORTED
  'uma zona para a qual já foi agendado um evento de limpeza, mas que ainda não foi limpa'
  CLEANING_SCHEDULED
  'zona que passou por um evento de limpeza e foi considerada limpa'
  CLEANED
}

' classes
class User {
  name: Name
  email: Email <<unique>>
  password: Password
}

class Zone {
  address: Address
  description: Description
  area: Location
  reported: Date
  photos: List<Photo>
  critical: Boolean
}

class Event {
  title: Title
  description: Description
  start: DateTime
  period: Duration
}

class Message {
  content: MessageContent
  timestamp: DateTime
}

' relações
User <- Event : organizer
User <- Zone : reporter
User <- Message : sender
User "*" -- "*" Event : participants <

Event --* Zone : events
Event *-- "*" Message : messages
Event -> EventStatus : status

Zone -up-> ZoneStatus : status

hide empty members

@enduml