name: Create Release and Build Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # --- JOB 2: ---
  build_desktop:
    name: Build Desktop Installer (${{ matrix.os }})
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print OS
        run: echo "Hello from ${{ runner.os }}"

      - name: Windows Specific Step
        if: runner.os == 'Windows'
        run: echo "This is a Windows-only step."

      - name: Unix Specific Step
        if: runner.os != 'Windows'
        run: echo "This is a Unix-only step."
